export LC_CTYPE=C
export PYTHONIOENCODING=utf-8

BASEROM_NAME := baserom
OUTPUT_NAME := dq4

# Tools/Toolchain
PYTHON := python3
NDSTOOL := ndstool

# Types
ROM_TYPE := nds
BIN_TYPE := bin

# Folders
ROOT_FOLDER := .
EXTRACT_FOLDER := $(ROOT_FOLDER)/_extract
BUILD_FOLDER := $(ROOT_FOLDER)/_build

# Binaries
BASEROM_FILE := $(BASEROM_NAME).$(ROM_TYPE)
TARGET_FILE := $(OUTPUT_NAME).$(ROM_TYPE)
BASE_ARM7_BIN := $(EXTRACT_FOLDER)/arm7.$(BIN_TYPE)
BASE_ARM9_BIN := $(EXTRACT_FOLDER)/arm9.$(BIN_TYPE)
BASE_ARM7_OVERLAY_BIN := $(EXTRACT_FOLDER)/arm7_overlay.$(BIN_TYPE)
BASE_ARM9_OVERLAY_BIN := $(EXTRACT_FOLDER)/arm9_overlay.$(BIN_TYPE)
BASE_HEADER_BIN := $(EXTRACT_FOLDER)/header.$(BIN_TYPE)
BASE_BANNER_BIN := $(EXTRACT_FOLDER)/banner.$(BIN_TYPE)
BASE_LOGO_BIN := $(EXTRACT_FOLDER)/logo.$(BIN_TYPE)
# For the extracted directories, rely on a stamp but still rely on all the files in those folders
BASE_DATA_DIRECTORY := $(EXTRACT_FOLDER)/data
BASE_DATA_DIRECTORY_STAMP := $(EXTRACT_FOLDER)/data.stamp
BASE_OVERLAY_DIRECTORY := $(EXTRACT_FOLDER)/overlay
BASE_OVERLAY_DIRECTORY_STAMP := $(EXTRACT_FOLDER)/overlay.stamp

EXTRACTED_FILES := $(BASE_ARM7_BIN) $(BASE_ARM9_BIN) $(BASE_ARM7_OVERLAY_BIN) $(BASE_ARM9_OVERLAY_BIN) $(BASE_HEADER_BIN) $(BASE_BANNER_BIN) $(BASE_LOGO_BIN) $(BASE_DATA_DIRECTORY_STAMP) $(BASE_OVERLAY_DIRECTORY_STAMP)

.PHONY: all clean default extract
default: all
all: $(TARGET_FILE)

clean:
	rm -rf $(TARGET_FILE)
	rm -rf $(BUILD_FOLDER)

.SECONDEXPANSION:
$(TARGET_FILE): $(EXTRACTED_FILES) $(wildcard $(BASE_DATA_DIRECTORY)/**/*) $(wildcard $(BASE_OVERLAY_DIRECTORY)/**/*)
	$(NDSTOOL) -c $@ -7 $(BASE_ARM7_BIN) -9 $(BASE_ARM9_BIN) -y7 $(BASE_ARM7_OVERLAY_BIN) -y9 $(BASE_ARM9_OVERLAY_BIN) -d $(BASE_DATA_DIRECTORY) -y $(BASE_OVERLAY_DIRECTORY) -h $(BASE_HEADER_BIN) -t $(BASE_BANNER_BIN) -o $(BASE_LOGO_BIN)

# Extraction
extract: $(EXTRACTED_FILES)

$(BASE_ARM7_BIN): $(BASEROM_FILE) | $(EXTRACT_FOLDER)
	$(NDSTOOL) -x $< -7 $@

$(BASE_ARM9_BIN): $(BASEROM_FILE) | $(EXTRACT_FOLDER)
	$(NDSTOOL) -x $< -9 $@

$(BASE_ARM7_OVERLAY_BIN): $(BASEROM_FILE) | $(EXTRACT_FOLDER)
	$(NDSTOOL) -x $< -y7 $@

$(BASE_ARM9_OVERLAY_BIN): $(BASEROM_FILE) | $(EXTRACT_FOLDER)
	$(NDSTOOL) -x $< -y9 $@

$(BASE_HEADER_BIN): $(BASEROM_FILE) | $(EXTRACT_FOLDER)
	$(NDSTOOL) -x $< -h $@

$(BASE_BANNER_BIN): $(BASEROM_FILE) | $(EXTRACT_FOLDER)
	$(NDSTOOL) -x $< -t $@

$(BASE_LOGO_BIN): $(BASEROM_FILE) | $(EXTRACT_FOLDER)
	$(NDSTOOL) -x $< -o $@

$(BASE_DATA_DIRECTORY_STAMP): $(BASEROM_FILE) | $(EXTRACT_FOLDER)
	$(NDSTOOL) -x $< -d $(BASE_DATA_DIRECTORY)
	touch $@

$(BASE_OVERLAY_DIRECTORY_STAMP): $(BASEROM_FILE) | $(EXTRACT_FOLDER)
	$(NDSTOOL) -x $< -y $(BASE_OVERLAY_DIRECTORY)
	touch $@

# Make directories if necessary
$(BUILD_FOLDER):
	mkdir -p $@

$(EXTRACT_FOLDER):
	mkdir -p $@